source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.0'

target 'DualSlideMenu_Example' do
  pod 'DualSlideMenu', :path => '../'
end

target 'DualSlideMenu_Tests' do
  pod 'DualSlideMenu', :path => '../'
end
