language: objective-c
osx_image: xcode7.3

branches:
 only:
  - master

before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail 
- xcodebuild clean test -workspace Example/DualSlideMenu.xcworkspace -scheme DualSlideMenu-Example -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" -enableCodeCoverage YES | xcpretty
- pod lib lint --allow-warnings

after_success:
  - bash <(curl -s https://codecov.io/bash)
