language: objective-c
osx_image: xcode7.3

branches:
 only:
  - master

before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail 
- xcodebuild clean build -workspace Example/DualSlideMenu.xcworkspace -scheme DualSlideMenu-Example -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" | xcpretty
- pod lib lint --allow-warnings
